defmodule Helpdesk.Repo.Migrations.AddTickets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :child_of_ticket_id,
          references(:tickets,
            column: :id,
            name: "tickets_child_of_ticket_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:tickets, "tickets_child_of_ticket_id_fkey")

    drop table(:tickets)
  end
end
