defmodule Helpdesk.Support.Ticket do
  # This turns this module into a resource
  use Ash.Resource, domain: Helpdesk.Support, data_layer: AshPostgres.DataLayer

  postgres do
    table "tickets"
    repo Helpdesk.Repo
  end

  actions do
    # Use the default implementation of the :read action
    defaults [:read]

    # and a create action, which we'll customize later
    create :create do
      primary? true

      accept [:child_of_ticket_id]

      change {Helpdesk.Changes.EnforceSingleLevelParenting,
              parent_key: :child_of_ticket_id, children_key: :ticket_children},
             where: [present(:child_of_ticket_id)]
    end

    update :update do
      primary? true
      require_atomic? false

      accept [:child_of_ticket_id]

      change {Helpdesk.Changes.EnforceSingleLevelParenting,
              parent_key: :child_of_ticket_id, children_key: :ticket_children},
             where: [changing(:child_of_ticket_id)]
    end
  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id
  end

  relationships do
    belongs_to :child_of_ticket, Helpdesk.Support.Ticket do
      allow_nil? true
    end

    has_many :ticket_children, Helpdesk.Support.Ticket do
      destination_attribute :child_of_ticket_id
    end
  end
end
